-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity boundary_check is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    pageOffsetFifo_V_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    pageOffsetFifo_V_empty_n : IN STD_LOGIC;
    pageOffsetFifo_V_read : OUT STD_LOGIC;
    cmdOut_V_TREADY : IN STD_LOGIC;
    cmdOut_V_TDATA : OUT STD_LOGIC_VECTOR (95 downto 0);
    cmdOut_V_TVALID : OUT STD_LOGIC );
end;


architecture behav of boundary_check is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_67 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100111";
    constant ap_const_lv32_68 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv33_200000 : STD_LOGIC_VECTOR (32 downto 0) := "000000000001000000000000000000000";
    constant ap_const_lv32_200000 : STD_LOGIC_VECTOR (31 downto 0) := "00000000001000000000000000000000";
    constant ap_const_lv48_200000 : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000001000000000000000000000";
    constant ap_const_lv32_FFE00000 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111000000000000000000000";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal bc_state_load_load_fu_181_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_nbreadreq_fu_74_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op10_read_state1 : BOOLEAN;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal bc_state_load_reg_350 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_364 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_1_reg_389 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op32_write_state2 : BOOLEAN;
    signal ap_predicate_op36_write_state2 : BOOLEAN;
    signal icmp_ln895_reg_393 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op43_write_state2 : BOOLEAN;
    signal ap_predicate_op45_write_state2 : BOOLEAN;
    signal ap_block_state2_io : BOOLEAN;
    signal regslice_both_cmdOut_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal bc_state_load_reg_350_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_364_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_1_reg_389_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op58_write_state3 : BOOLEAN;
    signal ap_predicate_op59_write_state3 : BOOLEAN;
    signal icmp_ln895_reg_393_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op60_write_state3 : BOOLEAN;
    signal ap_predicate_op61_write_state3 : BOOLEAN;
    signal ap_block_state3_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal bc_state : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal cmd_addr_V : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000000";
    signal cmd_len_V : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal cmdOut_V_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal pageOffsetFifo_V_blk_n : STD_LOGIC;
    signal cmd_addr_V_flag_2_i_reg_95 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmd_load_reg_354 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_len_V_reg_359 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln321_fu_193_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal trunc_ln321_reg_368 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_len_V_2_fu_197_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_len_V_2_reg_375 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_new_length_V_loa_reg_382 : STD_LOGIC_VECTOR (23 downto 0);
    signal icmp_ln895_1_fu_241_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_fu_253_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln700_fu_259_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal add_ln701_fu_265_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_280_p3 : STD_LOGIC_VECTOR (95 downto 0);
    signal tmp_1_fu_298_p1 : STD_LOGIC_VECTOR (95 downto 0);
    signal tmp_4_fu_321_p3 : STD_LOGIC_VECTOR (95 downto 0);
    signal tmp_3_fu_329_p3 : STD_LOGIC_VECTOR (95 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_phi_mux_cmd_addr_V_flag_2_i_phi_fu_98_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_cmd_addr_V_flag_2_i_reg_95 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_cmd_addr_V_new_2_i_reg_107 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_phi_reg_pp0_iter1_cmd_addr_V_new_2_i_reg_107 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_phi_reg_pp0_iter0_cmd_len_V_new_2_i_reg_118 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_cmd_len_V_new_2_i_reg_118 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_cmd_addr_V_flag_3_i_phi_fu_134_p8 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_cmd_addr_V_flag_3_i_reg_129 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_cmd_addr_V_flag_3_i_reg_129 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_cmd_addr_V_new_3_i_phi_fu_153_p8 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_phi_reg_pp0_iter1_cmd_addr_V_new_3_i_reg_149 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_phi_reg_pp0_iter0_cmd_addr_V_new_3_i_reg_149 : STD_LOGIC_VECTOR (47 downto 0);
    signal add_ln700_1_fu_306_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_phi_mux_cmd_len_V_new_3_i_phi_fu_169_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_cmd_len_V_new_3_i_reg_165 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_cmd_len_V_new_3_i_reg_165 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln701_fu_312_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_cmd_load : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_sig_allocacmp_tmp_len_V : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_page_offset_V_lo_fu_207_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal lhs_V_fu_227_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal rhs_V_fu_231_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal ret_V_fu_235_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp_addr_V_1_fu_277_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_5_i_fu_291_p3 : STD_LOGIC_VECTOR (87 downto 0);
    signal zext_ln700_fu_303_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_len_V_1_fu_288_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_addr_V_fu_318_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to1 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal cmdOut_V_TDATA_int : STD_LOGIC_VECTOR (95 downto 0);
    signal cmdOut_V_TVALID_int : STD_LOGIC;
    signal cmdOut_V_TREADY_int : STD_LOGIC;
    signal regslice_both_cmdOut_V_U_vld_out : STD_LOGIC;
    signal ap_condition_251 : BOOLEAN;
    signal ap_condition_140 : BOOLEAN;
    signal ap_condition_263 : BOOLEAN;
    signal ap_condition_281 : BOOLEAN;

    component regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_cmdOut_V_U : component regslice_both
    generic map (
        DataWidth => 96)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => cmdOut_V_TDATA_int,
        vld_in => cmdOut_V_TVALID_int,
        ack_in => cmdOut_V_TREADY_int,
        data_out => cmdOut_V_TDATA,
        vld_out => regslice_both_cmdOut_V_U_vld_out,
        ack_out => cmdOut_V_TREADY,
        apdone_blk => regslice_both_cmdOut_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_cmd_addr_V_flag_3_i_reg_129_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_140)) then
                if ((ap_const_boolean_1 = ap_condition_251)) then 
                    ap_phi_reg_pp0_iter1_cmd_addr_V_flag_3_i_reg_129 <= ap_const_lv1_1;
                elsif (((tmp_nbreadreq_fu_74_p3 = ap_const_lv1_0) and (bc_state = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_cmd_addr_V_flag_3_i_reg_129 <= ap_const_lv1_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_cmd_addr_V_flag_3_i_reg_129 <= ap_phi_reg_pp0_iter0_cmd_addr_V_flag_3_i_reg_129;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_cmd_addr_V_new_2_i_reg_107_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_140)) then
                if (((icmp_ln895_fu_253_p2 = ap_const_lv1_1) and (bc_state_load_load_fu_181_p1 = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter1_cmd_addr_V_new_2_i_reg_107 <= add_ln700_fu_259_p2;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_cmd_addr_V_new_2_i_reg_107 <= ap_phi_reg_pp0_iter0_cmd_addr_V_new_2_i_reg_107;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_cmd_addr_V_new_3_i_reg_149_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_140)) then
                if ((ap_const_boolean_1 = ap_condition_251)) then 
                    ap_phi_reg_pp0_iter1_cmd_addr_V_new_3_i_reg_149 <= trunc_ln321_fu_193_p1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_cmd_addr_V_new_3_i_reg_149 <= ap_phi_reg_pp0_iter0_cmd_addr_V_new_3_i_reg_149;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_cmd_len_V_new_2_i_reg_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_140)) then
                if (((icmp_ln895_fu_253_p2 = ap_const_lv1_1) and (bc_state_load_load_fu_181_p1 = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter1_cmd_len_V_new_2_i_reg_118 <= add_ln701_fu_265_p2;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_cmd_len_V_new_2_i_reg_118 <= ap_phi_reg_pp0_iter0_cmd_len_V_new_2_i_reg_118;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_cmd_len_V_new_3_i_reg_165_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_140)) then
                if ((ap_const_boolean_1 = ap_condition_251)) then 
                    ap_phi_reg_pp0_iter1_cmd_len_V_new_3_i_reg_165 <= pageOffsetFifo_V_dout(79 downto 48);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_cmd_len_V_new_3_i_reg_165 <= ap_phi_reg_pp0_iter0_cmd_len_V_new_3_i_reg_165;
                end if;
            end if; 
        end if;
    end process;

    bc_state_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_140)) then
                if ((bc_state_load_load_fu_181_p1 = ap_const_lv1_1)) then 
                    bc_state <= ap_phi_mux_cmd_addr_V_flag_2_i_phi_fu_98_p4;
                elsif ((ap_const_boolean_1 = ap_condition_263)) then 
                    bc_state <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;

    cmd_addr_V_flag_2_i_reg_95_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_140)) then
                if (((icmp_ln895_fu_253_p2 = ap_const_lv1_0) and (bc_state_load_load_fu_181_p1 = ap_const_lv1_1))) then 
                    cmd_addr_V_flag_2_i_reg_95 <= ap_const_lv1_0;
                elsif (((icmp_ln895_fu_253_p2 = ap_const_lv1_1) and (bc_state_load_load_fu_181_p1 = ap_const_lv1_1))) then 
                    cmd_addr_V_flag_2_i_reg_95 <= ap_const_lv1_1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    cmd_addr_V_flag_2_i_reg_95 <= ap_phi_reg_pp0_iter0_cmd_addr_V_flag_2_i_reg_95;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                bc_state_load_reg_350 <= bc_state;
                bc_state_load_reg_350_pp0_iter1_reg <= bc_state_load_reg_350;
                cmd_load_reg_354 <= ap_sig_allocacmp_cmd_load;
                icmp_ln895_1_reg_389_pp0_iter1_reg <= icmp_ln895_1_reg_389;
                icmp_ln895_reg_393_pp0_iter1_reg <= icmp_ln895_reg_393;
                tmp_len_V_reg_359 <= ap_sig_allocacmp_tmp_len_V;
                tmp_reg_364_pp0_iter1_reg <= tmp_reg_364;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_phi_mux_cmd_addr_V_flag_3_i_phi_fu_134_p8 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                cmd_addr_V <= ap_phi_mux_cmd_addr_V_new_3_i_phi_fu_153_p8;
                cmd_len_V <= ap_phi_mux_cmd_len_V_new_3_i_phi_fu_169_p8;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_nbreadreq_fu_74_p3 = ap_const_lv1_1) and (bc_state = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln895_1_reg_389 <= icmp_ln895_1_fu_241_p2;
                tmp_len_V_2_reg_375 <= pageOffsetFifo_V_dout(79 downto 48);
                tmp_new_length_V_loa_reg_382 <= pageOffsetFifo_V_dout(127 downto 104);
                trunc_ln321_reg_368 <= trunc_ln321_fu_193_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((bc_state_load_load_fu_181_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln895_reg_393 <= icmp_ln895_fu_253_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((bc_state = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_reg_364 <= tmp_nbreadreq_fu_74_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln700_1_fu_306_p2 <= std_logic_vector(unsigned(trunc_ln321_reg_368) + unsigned(zext_ln700_fu_303_p1));
    add_ln700_fu_259_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_cmd_load) + unsigned(ap_const_lv48_200000));
    add_ln701_fu_265_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_tmp_len_V) + unsigned(ap_const_lv32_FFE00000));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter2, pageOffsetFifo_V_empty_n, ap_predicate_op10_read_state1, regslice_both_cmdOut_V_U_apdone_blk)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((regslice_both_cmdOut_V_U_apdone_blk = ap_const_logic_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((pageOffsetFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op10_read_state1 = ap_const_boolean_1)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, pageOffsetFifo_V_empty_n, ap_predicate_op10_read_state1, ap_block_state2_io, regslice_both_cmdOut_V_U_apdone_blk, ap_block_state3_io)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_io)) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((pageOffsetFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op10_read_state1 = ap_const_boolean_1)))) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((regslice_both_cmdOut_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_io))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, pageOffsetFifo_V_empty_n, ap_predicate_op10_read_state1, ap_block_state2_io, regslice_both_cmdOut_V_U_apdone_blk, ap_block_state3_io)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_io)) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((pageOffsetFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op10_read_state1 = ap_const_boolean_1)))) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((regslice_both_cmdOut_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_io))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start, ap_done_reg, pageOffsetFifo_V_empty_n, ap_predicate_op10_read_state1)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((pageOffsetFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op10_read_state1 = ap_const_boolean_1)));
    end process;


    ap_block_state2_io_assign_proc : process(ap_predicate_op32_write_state2, ap_predicate_op36_write_state2, ap_predicate_op43_write_state2, ap_predicate_op45_write_state2, cmdOut_V_TREADY_int)
    begin
                ap_block_state2_io <= (((cmdOut_V_TREADY_int = ap_const_logic_0) and (ap_predicate_op45_write_state2 = ap_const_boolean_1)) or ((cmdOut_V_TREADY_int = ap_const_logic_0) and (ap_predicate_op43_write_state2 = ap_const_boolean_1)) or ((cmdOut_V_TREADY_int = ap_const_logic_0) and (ap_predicate_op36_write_state2 = ap_const_boolean_1)) or ((cmdOut_V_TREADY_int = ap_const_logic_0) and (ap_predicate_op32_write_state2 = ap_const_boolean_1)));
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_io_assign_proc : process(ap_predicate_op58_write_state3, ap_predicate_op59_write_state3, ap_predicate_op60_write_state3, ap_predicate_op61_write_state3, cmdOut_V_TREADY_int)
    begin
                ap_block_state3_io <= (((cmdOut_V_TREADY_int = ap_const_logic_0) and (ap_predicate_op61_write_state3 = ap_const_boolean_1)) or ((cmdOut_V_TREADY_int = ap_const_logic_0) and (ap_predicate_op60_write_state3 = ap_const_boolean_1)) or ((cmdOut_V_TREADY_int = ap_const_logic_0) and (ap_predicate_op59_write_state3 = ap_const_boolean_1)) or ((cmdOut_V_TREADY_int = ap_const_logic_0) and (ap_predicate_op58_write_state3 = ap_const_boolean_1)));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(regslice_both_cmdOut_V_U_apdone_blk)
    begin
                ap_block_state3_pp0_stage0_iter2 <= (regslice_both_cmdOut_V_U_apdone_blk = ap_const_logic_1);
    end process;


    ap_condition_140_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_140 <= ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001));
    end process;


    ap_condition_251_assign_proc : process(tmp_nbreadreq_fu_74_p3, bc_state, icmp_ln895_1_fu_241_p2)
    begin
                ap_condition_251 <= ((tmp_nbreadreq_fu_74_p3 = ap_const_lv1_1) and (icmp_ln895_1_fu_241_p2 = ap_const_lv1_0) and (bc_state = ap_const_lv1_0));
    end process;


    ap_condition_263_assign_proc : process(tmp_nbreadreq_fu_74_p3, bc_state, icmp_ln895_1_fu_241_p2)
    begin
                ap_condition_263 <= ((icmp_ln895_1_fu_241_p2 = ap_const_lv1_1) and (tmp_nbreadreq_fu_74_p3 = ap_const_lv1_1) and (bc_state = ap_const_lv1_0));
    end process;


    ap_condition_281_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_01001)
    begin
                ap_condition_281 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_cmd_addr_V_flag_2_i_phi_fu_98_p4_assign_proc : process(bc_state_load_load_fu_181_p1, icmp_ln895_fu_253_p2, ap_phi_reg_pp0_iter0_cmd_addr_V_flag_2_i_reg_95)
    begin
        if ((bc_state_load_load_fu_181_p1 = ap_const_lv1_1)) then
            if ((icmp_ln895_fu_253_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_cmd_addr_V_flag_2_i_phi_fu_98_p4 <= ap_const_lv1_0;
            elsif ((icmp_ln895_fu_253_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_cmd_addr_V_flag_2_i_phi_fu_98_p4 <= ap_const_lv1_1;
            else 
                ap_phi_mux_cmd_addr_V_flag_2_i_phi_fu_98_p4 <= ap_phi_reg_pp0_iter0_cmd_addr_V_flag_2_i_reg_95;
            end if;
        else 
            ap_phi_mux_cmd_addr_V_flag_2_i_phi_fu_98_p4 <= ap_phi_reg_pp0_iter0_cmd_addr_V_flag_2_i_reg_95;
        end if; 
    end process;


    ap_phi_mux_cmd_addr_V_flag_3_i_phi_fu_134_p8_assign_proc : process(bc_state_load_reg_350, tmp_reg_364, icmp_ln895_1_reg_389, cmd_addr_V_flag_2_i_reg_95, ap_phi_reg_pp0_iter1_cmd_addr_V_flag_3_i_reg_129)
    begin
        if (((icmp_ln895_1_reg_389 = ap_const_lv1_1) and (tmp_reg_364 = ap_const_lv1_1) and (bc_state_load_reg_350 = ap_const_lv1_0))) then 
            ap_phi_mux_cmd_addr_V_flag_3_i_phi_fu_134_p8 <= ap_const_lv1_1;
        elsif ((bc_state_load_reg_350 = ap_const_lv1_1)) then 
            ap_phi_mux_cmd_addr_V_flag_3_i_phi_fu_134_p8 <= cmd_addr_V_flag_2_i_reg_95;
        else 
            ap_phi_mux_cmd_addr_V_flag_3_i_phi_fu_134_p8 <= ap_phi_reg_pp0_iter1_cmd_addr_V_flag_3_i_reg_129;
        end if; 
    end process;


    ap_phi_mux_cmd_addr_V_new_3_i_phi_fu_153_p8_assign_proc : process(bc_state_load_reg_350, tmp_reg_364, icmp_ln895_1_reg_389, ap_phi_reg_pp0_iter1_cmd_addr_V_new_2_i_reg_107, ap_phi_reg_pp0_iter1_cmd_addr_V_new_3_i_reg_149, add_ln700_1_fu_306_p2)
    begin
        if (((icmp_ln895_1_reg_389 = ap_const_lv1_1) and (tmp_reg_364 = ap_const_lv1_1) and (bc_state_load_reg_350 = ap_const_lv1_0))) then 
            ap_phi_mux_cmd_addr_V_new_3_i_phi_fu_153_p8 <= add_ln700_1_fu_306_p2;
        elsif ((bc_state_load_reg_350 = ap_const_lv1_1)) then 
            ap_phi_mux_cmd_addr_V_new_3_i_phi_fu_153_p8 <= ap_phi_reg_pp0_iter1_cmd_addr_V_new_2_i_reg_107;
        else 
            ap_phi_mux_cmd_addr_V_new_3_i_phi_fu_153_p8 <= ap_phi_reg_pp0_iter1_cmd_addr_V_new_3_i_reg_149;
        end if; 
    end process;


    ap_phi_mux_cmd_len_V_new_3_i_phi_fu_169_p8_assign_proc : process(bc_state_load_reg_350, tmp_reg_364, icmp_ln895_1_reg_389, ap_phi_reg_pp0_iter1_cmd_len_V_new_2_i_reg_118, ap_phi_reg_pp0_iter1_cmd_len_V_new_3_i_reg_165, sub_ln701_fu_312_p2)
    begin
        if (((icmp_ln895_1_reg_389 = ap_const_lv1_1) and (tmp_reg_364 = ap_const_lv1_1) and (bc_state_load_reg_350 = ap_const_lv1_0))) then 
            ap_phi_mux_cmd_len_V_new_3_i_phi_fu_169_p8 <= sub_ln701_fu_312_p2;
        elsif ((bc_state_load_reg_350 = ap_const_lv1_1)) then 
            ap_phi_mux_cmd_len_V_new_3_i_phi_fu_169_p8 <= ap_phi_reg_pp0_iter1_cmd_len_V_new_2_i_reg_118;
        else 
            ap_phi_mux_cmd_len_V_new_3_i_phi_fu_169_p8 <= ap_phi_reg_pp0_iter1_cmd_len_V_new_3_i_reg_165;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_cmd_addr_V_flag_2_i_reg_95 <= "X";
    ap_phi_reg_pp0_iter0_cmd_addr_V_flag_3_i_reg_129 <= "X";
    ap_phi_reg_pp0_iter0_cmd_addr_V_new_2_i_reg_107 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_cmd_addr_V_new_3_i_reg_149 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_cmd_len_V_new_2_i_reg_118 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_cmd_len_V_new_3_i_reg_165 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op10_read_state1_assign_proc : process(tmp_nbreadreq_fu_74_p3, bc_state)
    begin
                ap_predicate_op10_read_state1 <= ((tmp_nbreadreq_fu_74_p3 = ap_const_lv1_1) and (bc_state = ap_const_lv1_0));
    end process;


    ap_predicate_op32_write_state2_assign_proc : process(bc_state_load_reg_350, tmp_reg_364, icmp_ln895_1_reg_389)
    begin
                ap_predicate_op32_write_state2 <= ((tmp_reg_364 = ap_const_lv1_1) and (icmp_ln895_1_reg_389 = ap_const_lv1_0) and (bc_state_load_reg_350 = ap_const_lv1_0));
    end process;


    ap_predicate_op36_write_state2_assign_proc : process(bc_state_load_reg_350, tmp_reg_364, icmp_ln895_1_reg_389)
    begin
                ap_predicate_op36_write_state2 <= ((icmp_ln895_1_reg_389 = ap_const_lv1_1) and (tmp_reg_364 = ap_const_lv1_1) and (bc_state_load_reg_350 = ap_const_lv1_0));
    end process;


    ap_predicate_op43_write_state2_assign_proc : process(bc_state_load_reg_350, icmp_ln895_reg_393)
    begin
                ap_predicate_op43_write_state2 <= ((bc_state_load_reg_350 = ap_const_lv1_1) and (icmp_ln895_reg_393 = ap_const_lv1_0));
    end process;


    ap_predicate_op45_write_state2_assign_proc : process(bc_state_load_reg_350, icmp_ln895_reg_393)
    begin
                ap_predicate_op45_write_state2 <= ((icmp_ln895_reg_393 = ap_const_lv1_1) and (bc_state_load_reg_350 = ap_const_lv1_1));
    end process;


    ap_predicate_op58_write_state3_assign_proc : process(bc_state_load_reg_350_pp0_iter1_reg, tmp_reg_364_pp0_iter1_reg, icmp_ln895_1_reg_389_pp0_iter1_reg)
    begin
                ap_predicate_op58_write_state3 <= ((tmp_reg_364_pp0_iter1_reg = ap_const_lv1_1) and (bc_state_load_reg_350_pp0_iter1_reg = ap_const_lv1_0) and (icmp_ln895_1_reg_389_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op59_write_state3_assign_proc : process(bc_state_load_reg_350_pp0_iter1_reg, tmp_reg_364_pp0_iter1_reg, icmp_ln895_1_reg_389_pp0_iter1_reg)
    begin
                ap_predicate_op59_write_state3 <= ((icmp_ln895_1_reg_389_pp0_iter1_reg = ap_const_lv1_1) and (tmp_reg_364_pp0_iter1_reg = ap_const_lv1_1) and (bc_state_load_reg_350_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op60_write_state3_assign_proc : process(bc_state_load_reg_350_pp0_iter1_reg, icmp_ln895_reg_393_pp0_iter1_reg)
    begin
                ap_predicate_op60_write_state3 <= ((bc_state_load_reg_350_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln895_reg_393_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op61_write_state3_assign_proc : process(bc_state_load_reg_350_pp0_iter1_reg, icmp_ln895_reg_393_pp0_iter1_reg)
    begin
                ap_predicate_op61_write_state3 <= ((bc_state_load_reg_350_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln895_reg_393_pp0_iter1_reg = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to1 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_cmd_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, cmd_addr_V, ap_block_pp0_stage0, ap_phi_mux_cmd_addr_V_flag_3_i_phi_fu_134_p8, ap_phi_mux_cmd_addr_V_new_3_i_phi_fu_153_p8)
    begin
        if (((ap_phi_mux_cmd_addr_V_flag_3_i_phi_fu_134_p8 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_cmd_load <= ap_phi_mux_cmd_addr_V_new_3_i_phi_fu_153_p8;
        else 
            ap_sig_allocacmp_cmd_load <= cmd_addr_V;
        end if; 
    end process;


    ap_sig_allocacmp_tmp_len_V_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, cmd_len_V, ap_block_pp0_stage0, ap_phi_mux_cmd_addr_V_flag_3_i_phi_fu_134_p8, ap_phi_mux_cmd_len_V_new_3_i_phi_fu_169_p8)
    begin
        if (((ap_phi_mux_cmd_addr_V_flag_3_i_phi_fu_134_p8 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_tmp_len_V <= ap_phi_mux_cmd_len_V_new_3_i_phi_fu_169_p8;
        else 
            ap_sig_allocacmp_tmp_len_V <= cmd_len_V;
        end if; 
    end process;

    bc_state_load_load_fu_181_p1 <= bc_state;

    cmdOut_V_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_predicate_op32_write_state2, ap_predicate_op36_write_state2, ap_predicate_op43_write_state2, ap_predicate_op45_write_state2, ap_predicate_op58_write_state3, ap_predicate_op59_write_state3, ap_predicate_op60_write_state3, ap_predicate_op61_write_state3, ap_block_pp0_stage0, cmdOut_V_TREADY_int)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op45_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op43_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op36_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op32_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_predicate_op61_write_state3 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_predicate_op60_write_state3 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_predicate_op59_write_state3 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_predicate_op58_write_state3 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            cmdOut_V_TDATA_blk_n <= cmdOut_V_TREADY_int;
        else 
            cmdOut_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    cmdOut_V_TDATA_int_assign_proc : process(ap_predicate_op32_write_state2, ap_predicate_op36_write_state2, ap_predicate_op43_write_state2, ap_predicate_op45_write_state2, tmp_2_fu_280_p3, tmp_1_fu_298_p1, tmp_4_fu_321_p3, tmp_3_fu_329_p3, ap_condition_281)
    begin
        if ((ap_const_boolean_1 = ap_condition_281)) then
            if ((ap_predicate_op45_write_state2 = ap_const_boolean_1)) then 
                cmdOut_V_TDATA_int <= tmp_3_fu_329_p3;
            elsif ((ap_predicate_op43_write_state2 = ap_const_boolean_1)) then 
                cmdOut_V_TDATA_int <= tmp_4_fu_321_p3;
            elsif ((ap_predicate_op36_write_state2 = ap_const_boolean_1)) then 
                cmdOut_V_TDATA_int <= tmp_1_fu_298_p1;
            elsif ((ap_predicate_op32_write_state2 = ap_const_boolean_1)) then 
                cmdOut_V_TDATA_int <= tmp_2_fu_280_p3;
            else 
                cmdOut_V_TDATA_int <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            cmdOut_V_TDATA_int <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    cmdOut_V_TVALID <= regslice_both_cmdOut_V_U_vld_out;

    cmdOut_V_TVALID_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op32_write_state2, ap_predicate_op36_write_state2, ap_predicate_op43_write_state2, ap_predicate_op45_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op45_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op43_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op36_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op32_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            cmdOut_V_TVALID_int <= ap_const_logic_1;
        else 
            cmdOut_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln895_1_fu_241_p2 <= "1" when (unsigned(ret_V_fu_235_p2) > unsigned(ap_const_lv33_200000)) else "0";
    icmp_ln895_fu_253_p2 <= "1" when (unsigned(ap_sig_allocacmp_tmp_len_V) > unsigned(ap_const_lv32_200000)) else "0";
    lhs_V_fu_227_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_page_offset_V_lo_fu_207_p4),33));

    pageOffsetFifo_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, pageOffsetFifo_V_empty_n, ap_predicate_op10_read_state1, ap_block_pp0_stage0)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op10_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            pageOffsetFifo_V_blk_n <= pageOffsetFifo_V_empty_n;
        else 
            pageOffsetFifo_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    pageOffsetFifo_V_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_predicate_op10_read_state1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op10_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            pageOffsetFifo_V_read <= ap_const_logic_1;
        else 
            pageOffsetFifo_V_read <= ap_const_logic_0;
        end if; 
    end process;

    ret_V_fu_235_p2 <= std_logic_vector(unsigned(lhs_V_fu_227_p1) + unsigned(rhs_V_fu_231_p1));
    rhs_V_fu_231_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_len_V_2_fu_197_p4),33));
    sub_ln701_fu_312_p2 <= std_logic_vector(unsigned(tmp_len_V_2_reg_375) - unsigned(tmp_len_V_1_fu_288_p1));
    tmp_1_fu_298_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_i_fu_291_p3),96));
    tmp_2_fu_280_p3 <= (tmp_len_V_2_reg_375 & tmp_addr_V_1_fu_277_p1);
    tmp_3_fu_329_p3 <= (ap_const_lv32_200000 & tmp_addr_V_fu_318_p1);
    tmp_4_fu_321_p3 <= (tmp_len_V_reg_359 & tmp_addr_V_fu_318_p1);
    tmp_5_i_fu_291_p3 <= (tmp_new_length_V_loa_reg_382 & tmp_addr_V_1_fu_277_p1);
    tmp_addr_V_1_fu_277_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln321_reg_368),64));
    tmp_addr_V_fu_318_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cmd_load_reg_354),64));
    tmp_len_V_1_fu_288_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_new_length_V_loa_reg_382),32));
    tmp_len_V_2_fu_197_p4 <= pageOffsetFifo_V_dout(79 downto 48);
    tmp_nbreadreq_fu_74_p3 <= (0=>(pageOffsetFifo_V_empty_n), others=>'-');
    tmp_page_offset_V_lo_fu_207_p4 <= pageOffsetFifo_V_dout(103 downto 80);
    trunc_ln321_fu_193_p1 <= pageOffsetFifo_V_dout(48 - 1 downto 0);
    zext_ln700_fu_303_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_new_length_V_loa_reg_382),48));
end behav;
