-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity tlb is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_axis_mem_write_cmd_V_TDATA : IN STD_LOGIC_VECTOR (95 downto 0);
    s_axis_mem_write_cmd_V_TVALID : IN STD_LOGIC;
    s_axis_mem_write_cmd_V_TREADY : OUT STD_LOGIC;
    s_axis_mem_read_cmd_V_TDATA : IN STD_LOGIC_VECTOR (95 downto 0);
    s_axis_mem_read_cmd_V_TVALID : IN STD_LOGIC;
    s_axis_mem_read_cmd_V_TREADY : OUT STD_LOGIC;
    m_axis_dma_write_cmd_V_TDATA : OUT STD_LOGIC_VECTOR (95 downto 0);
    m_axis_dma_write_cmd_V_TVALID : OUT STD_LOGIC;
    m_axis_dma_write_cmd_V_TREADY : IN STD_LOGIC;
    m_axis_dma_read_cmd_V_TDATA : OUT STD_LOGIC_VECTOR (95 downto 0);
    m_axis_dma_read_cmd_V_TVALID : OUT STD_LOGIC;
    m_axis_dma_read_cmd_V_TREADY : IN STD_LOGIC;
    s_axis_tlb_interface_V_TDATA : IN STD_LOGIC_VECTOR (135 downto 0);
    s_axis_tlb_interface_V_TVALID : IN STD_LOGIC;
    s_axis_tlb_interface_V_TREADY : OUT STD_LOGIC;
    regTlbMissCount_V : OUT STD_LOGIC_VECTOR (31 downto 0);
    regTlbMissCount_V_ap_vld : OUT STD_LOGIC;
    regPageCrossingCount_V : OUT STD_LOGIC_VECTOR (31 downto 0);
    regPageCrossingCount_V_ap_vld : OUT STD_LOGIC );
end;


architecture behav of tlb is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "tlb,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcu280-fsvh2892-2L-e,HLS_INPUT_CLOCK=3.200000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=2.305000,HLS_SYN_LAT=3,HLS_SYN_TPT=1,HLS_SYN_MEM=43,HLS_SYN_DSP=0,HLS_SYN_FF=825,HLS_SYN_LUT=780,HLS_VERSION=2020_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_5B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011011";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv33_200000 : STD_LOGIC_VECTOR (32 downto 0) := "000000000001000000000000000000000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal base_vaddr_V : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal top_page_base_V : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal tlbMissCounter_V : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal tlbPageCrossingCount : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal tlb_table_paddr_V_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal tlb_table_paddr_V_ce0 : STD_LOGIC;
    signal tlb_table_paddr_V_we0 : STD_LOGIC;
    signal tlb_table_paddr_V_q0 : STD_LOGIC_VECTOR (47 downto 0);
    signal s_axis_mem_write_cmd_V_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal tmp_nbreadreq_fu_94_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal s_axis_mem_read_cmd_V_TDATA_blk_n : STD_LOGIC;
    signal tmp_1_nbreadreq_fu_102_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_dma_write_cmd_V_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal tmp_reg_526 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_526_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal tmp_reg_526_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_dma_read_cmd_V_TDATA_blk_n : STD_LOGIC;
    signal tmp_1_reg_535 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_reg_535_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_reg_535_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal s_axis_tlb_interface_V_TDATA_blk_n : STD_LOGIC;
    signal tmp_2_nbreadreq_fu_110_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op12_read_state1 : BOOLEAN;
    signal ap_predicate_op19_read_state1 : BOOLEAN;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_predicate_op74_write_state3 : BOOLEAN;
    signal ap_block_state3_io : BOOLEAN;
    signal regslice_both_m_axis_dma_write_cmd_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_m_axis_dma_read_cmd_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_predicate_op105_write_state4 : BOOLEAN;
    signal ap_block_state4_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_2_reg_539 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln321_2_fu_230_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln321_2_reg_543 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln209_2_reg_552 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_len_V_2_load_new_reg_557 : STD_LOGIC_VECTOR (31 downto 0);
    signal page_offset_V_1_fu_278_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal page_offset_V_1_reg_562 : STD_LOGIC_VECTOR (20 downto 0);
    signal page_offset_V_1_reg_562_pp0_iter1_reg : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_1_reg_568 : STD_LOGIC_VECTOR (42 downto 0);
    signal tmp_len_V_1_reg_574 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_len_V_1_reg_574_pp0_iter1_reg : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_len_V_load_new_reg_579 : STD_LOGIC_VECTOR (31 downto 0);
    signal page_offset_V_fu_322_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal page_offset_V_reg_584 : STD_LOGIC_VECTOR (20 downto 0);
    signal page_offset_V_reg_584_pp0_iter1_reg : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_reg_590 : STD_LOGIC_VECTOR (42 downto 0);
    signal tmp_len_V_reg_596 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_len_V_reg_596_pp0_iter1_reg : STD_LOGIC_VECTOR (27 downto 0);
    signal icmp_ln895_4_fu_374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_2_fu_404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_2_reg_610 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_2_reg_610_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_3_fu_421_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_3_reg_614 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_3_reg_614_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_fu_435_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_reg_623 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_reg_623_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_1_fu_452_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_1_reg_627 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_1_reg_627_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_phi_reg_pp0_iter0_base_vaddr_V_loc_0_reg_193 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_reg_pp0_iter1_base_vaddr_V_loc_0_reg_193 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_4_fu_234_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_8_fu_365_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal r_V_7_fu_396_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal r_V_6_fu_427_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_202_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_214_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal trunc_ln321_1_fu_258_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal addr_V_1_fu_272_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln321_fu_302_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal addr_V_fu_316_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal addr_V_2_fu_350_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal r_V_2_fu_355_p4 : STD_LOGIC_VECTOR (42 downto 0);
    signal zext_ln895_2_fu_370_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal zext_ln895_1_fu_400_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal zext_ln215_2_fu_409_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln215_3_fu_412_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal ret_V_1_fu_415_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln895_fu_431_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal zext_ln215_fu_440_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln215_1_fu_443_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal ret_V_fu_446_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln78_2_fu_461_p1 : STD_LOGIC_VECTOR (48 downto 0);
    signal zext_ln214_1_fu_458_p1 : STD_LOGIC_VECTOR (48 downto 0);
    signal tmp_addr_V_1_fu_465_p2 : STD_LOGIC_VECTOR (48 downto 0);
    signal zext_ln78_3_fu_471_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_3_fu_475_p3 : STD_LOGIC_VECTOR (91 downto 0);
    signal zext_ln78_fu_490_p1 : STD_LOGIC_VECTOR (48 downto 0);
    signal zext_ln214_fu_487_p1 : STD_LOGIC_VECTOR (48 downto 0);
    signal tmp_addr_V_fu_494_p2 : STD_LOGIC_VECTOR (48 downto 0);
    signal zext_ln78_1_fu_500_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_12_fu_504_p3 : STD_LOGIC_VECTOR (91 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal m_axis_dma_write_cmd_V_TDATA_int : STD_LOGIC_VECTOR (95 downto 0);
    signal m_axis_dma_write_cmd_V_TVALID_int : STD_LOGIC;
    signal m_axis_dma_write_cmd_V_TREADY_int : STD_LOGIC;
    signal regslice_both_m_axis_dma_write_cmd_V_U_vld_out : STD_LOGIC;
    signal m_axis_dma_read_cmd_V_TDATA_int : STD_LOGIC_VECTOR (95 downto 0);
    signal m_axis_dma_read_cmd_V_TVALID_int : STD_LOGIC;
    signal m_axis_dma_read_cmd_V_TREADY_int : STD_LOGIC;
    signal regslice_both_m_axis_dma_read_cmd_V_U_vld_out : STD_LOGIC;
    signal ap_condition_247 : BOOLEAN;
    signal ap_condition_253 : BOOLEAN;
    signal ap_condition_244 : BOOLEAN;
    signal ap_condition_202 : BOOLEAN;
    signal ap_condition_257 : BOOLEAN;

    component tlb_tlb_table_padbkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (13 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (47 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (47 downto 0) );
    end component;


    component regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    tlb_table_paddr_V_U : component tlb_tlb_table_padbkb
    generic map (
        DataWidth => 48,
        AddressRange => 16384,
        AddressWidth => 14)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => tlb_table_paddr_V_address0,
        ce0 => tlb_table_paddr_V_ce0,
        we0 => tlb_table_paddr_V_we0,
        d0 => trunc_ln209_2_reg_552,
        q0 => tlb_table_paddr_V_q0);

    regslice_both_m_axis_dma_write_cmd_V_U : component regslice_both
    generic map (
        DataWidth => 96)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => m_axis_dma_write_cmd_V_TDATA_int,
        vld_in => m_axis_dma_write_cmd_V_TVALID_int,
        ack_in => m_axis_dma_write_cmd_V_TREADY_int,
        data_out => m_axis_dma_write_cmd_V_TDATA,
        vld_out => regslice_both_m_axis_dma_write_cmd_V_U_vld_out,
        ack_out => m_axis_dma_write_cmd_V_TREADY,
        apdone_blk => regslice_both_m_axis_dma_write_cmd_V_U_apdone_blk);

    regslice_both_m_axis_dma_read_cmd_V_U : component regslice_both
    generic map (
        DataWidth => 96)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => m_axis_dma_read_cmd_V_TDATA_int,
        vld_in => m_axis_dma_read_cmd_V_TVALID_int,
        ack_in => m_axis_dma_read_cmd_V_TREADY_int,
        data_out => m_axis_dma_read_cmd_V_TDATA,
        vld_out => regslice_both_m_axis_dma_read_cmd_V_U_vld_out,
        ack_out => m_axis_dma_read_cmd_V_TREADY,
        apdone_blk => regslice_both_m_axis_dma_read_cmd_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_base_vaddr_V_loc_0_reg_193_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_244)) then
                if ((ap_const_boolean_1 = ap_condition_253)) then 
                    ap_phi_reg_pp0_iter1_base_vaddr_V_loc_0_reg_193 <= base_vaddr_V;
                elsif ((ap_const_boolean_1 = ap_condition_247)) then 
                    ap_phi_reg_pp0_iter1_base_vaddr_V_loc_0_reg_193 <= trunc_ln321_2_fu_230_p1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_base_vaddr_V_loc_0_reg_193 <= ap_phi_reg_pp0_iter0_base_vaddr_V_loc_0_reg_193;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_1_nbreadreq_fu_102_p3 = ap_const_lv1_0) and (tmp_4_fu_234_p3 = ap_const_lv1_1) and (tmp_2_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (tmp_nbreadreq_fu_94_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                base_vaddr_V <= trunc_ln321_2_fu_230_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_reg_526 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln895_1_reg_627 <= icmp_ln895_1_fu_452_p2;
                icmp_ln895_reg_623 <= icmp_ln895_fu_435_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln895_1_reg_627_pp0_iter2_reg <= icmp_ln895_1_reg_627;
                icmp_ln895_2_reg_610_pp0_iter2_reg <= icmp_ln895_2_reg_610;
                icmp_ln895_3_reg_614_pp0_iter2_reg <= icmp_ln895_3_reg_614;
                icmp_ln895_reg_623_pp0_iter2_reg <= icmp_ln895_reg_623;
                tmp_1_reg_535_pp0_iter2_reg <= tmp_1_reg_535_pp0_iter1_reg;
                tmp_reg_526_pp0_iter2_reg <= tmp_reg_526_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_reg_526 = ap_const_lv1_0) and (tmp_1_reg_535 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln895_2_reg_610 <= icmp_ln895_2_fu_404_p2;
                icmp_ln895_3_reg_614 <= icmp_ln895_3_fu_421_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_1_nbreadreq_fu_102_p3 = ap_const_lv1_1) and (tmp_nbreadreq_fu_94_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                page_offset_V_1_reg_562 <= page_offset_V_1_fu_278_p1;
                r_V_1_reg_568 <= addr_V_1_fu_272_p2(63 downto 21);
                tmp_len_V_1_reg_574 <= s_axis_mem_read_cmd_V_TDATA(91 downto 64);
                tmp_len_V_2_load_new_reg_557 <= s_axis_mem_read_cmd_V_TDATA(95 downto 64);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                page_offset_V_1_reg_562_pp0_iter1_reg <= page_offset_V_1_reg_562;
                page_offset_V_reg_584_pp0_iter1_reg <= page_offset_V_reg_584;
                tmp_1_reg_535_pp0_iter1_reg <= tmp_1_reg_535;
                tmp_len_V_1_reg_574_pp0_iter1_reg <= tmp_len_V_1_reg_574;
                tmp_len_V_reg_596_pp0_iter1_reg <= tmp_len_V_reg_596;
                tmp_reg_526 <= tmp_nbreadreq_fu_94_p3;
                tmp_reg_526_pp0_iter1_reg <= tmp_reg_526;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_nbreadreq_fu_94_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                page_offset_V_reg_584 <= page_offset_V_fu_322_p1;
                r_V_reg_590 <= addr_V_fu_316_p2(63 downto 21);
                tmp_len_V_load_new_reg_579 <= s_axis_mem_write_cmd_V_TDATA(95 downto 64);
                tmp_len_V_reg_596 <= s_axis_mem_write_cmd_V_TDATA(91 downto 64);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((tmp_reg_526_pp0_iter2_reg = ap_const_lv1_0) and (tmp_1_reg_535_pp0_iter2_reg = ap_const_lv1_1) and (icmp_ln895_2_reg_610_pp0_iter2_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_reg_526_pp0_iter2_reg = ap_const_lv1_1) and (icmp_ln895_reg_623_pp0_iter2_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then
                tlbMissCounter_V <= grp_fu_202_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((tmp_reg_526_pp0_iter2_reg = ap_const_lv1_0) and (tmp_1_reg_535_pp0_iter2_reg = ap_const_lv1_1) and (icmp_ln895_3_reg_614_pp0_iter2_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_reg_526_pp0_iter2_reg = ap_const_lv1_1) and (icmp_ln895_1_reg_627_pp0_iter2_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then
                tlbPageCrossingCount <= grp_fu_214_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_nbreadreq_fu_94_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_1_reg_535 <= tmp_1_nbreadreq_fu_102_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_1_nbreadreq_fu_102_p3 = ap_const_lv1_0) and (tmp_nbreadreq_fu_94_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_2_reg_539 <= tmp_2_nbreadreq_fu_110_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_1_reg_535 = ap_const_lv1_0) and (tmp_reg_526 = ap_const_lv1_0) and (icmp_ln895_4_fu_374_p2 = ap_const_lv1_1) and (tmp_2_reg_539 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                top_page_base_V <= addr_V_2_fu_350_p2(52 downto 21);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_1_nbreadreq_fu_102_p3 = ap_const_lv1_0) and (tmp_2_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (tmp_nbreadreq_fu_94_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                trunc_ln209_2_reg_552 <= s_axis_tlb_interface_V_TDATA(111 downto 64);
                trunc_ln321_2_reg_543 <= trunc_ln321_2_fu_230_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    addr_V_1_fu_272_p2 <= std_logic_vector(unsigned(trunc_ln321_1_fu_258_p1) - unsigned(base_vaddr_V));
    addr_V_2_fu_350_p2 <= std_logic_vector(unsigned(trunc_ln321_2_reg_543) - unsigned(ap_phi_reg_pp0_iter1_base_vaddr_V_loc_0_reg_193));
    addr_V_fu_316_p2 <= std_logic_vector(unsigned(trunc_ln321_fu_302_p1) - unsigned(base_vaddr_V));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(s_axis_mem_write_cmd_V_TVALID, s_axis_mem_read_cmd_V_TVALID, s_axis_tlb_interface_V_TVALID, tmp_nbreadreq_fu_94_p3, ap_enable_reg_pp0_iter3, ap_predicate_op12_read_state1, ap_predicate_op19_read_state1, regslice_both_m_axis_dma_write_cmd_V_U_apdone_blk, regslice_both_m_axis_dma_read_cmd_V_U_apdone_blk)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and ((regslice_both_m_axis_dma_read_cmd_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_m_axis_dma_write_cmd_V_U_apdone_blk = ap_const_logic_1))) or ((ap_const_logic_1 = ap_const_logic_1) and (((tmp_nbreadreq_fu_94_p3 = ap_const_lv1_1) and (s_axis_mem_write_cmd_V_TVALID = ap_const_logic_0)) or ((ap_predicate_op19_read_state1 = ap_const_boolean_1) and (s_axis_mem_read_cmd_V_TVALID = ap_const_logic_0)) or ((ap_predicate_op12_read_state1 = ap_const_boolean_1) and (s_axis_tlb_interface_V_TVALID = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(s_axis_mem_write_cmd_V_TVALID, s_axis_mem_read_cmd_V_TVALID, s_axis_tlb_interface_V_TVALID, tmp_nbreadreq_fu_94_p3, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_predicate_op12_read_state1, ap_predicate_op19_read_state1, ap_block_state3_io, regslice_both_m_axis_dma_write_cmd_V_U_apdone_blk, regslice_both_m_axis_dma_read_cmd_V_U_apdone_blk, ap_block_state4_io)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state4_io) or (regslice_both_m_axis_dma_read_cmd_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_m_axis_dma_write_cmd_V_U_apdone_blk = ap_const_logic_1))) or ((ap_const_boolean_1 = ap_block_state3_io) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_logic_1 = ap_const_logic_1) and (((tmp_nbreadreq_fu_94_p3 = ap_const_lv1_1) and (s_axis_mem_write_cmd_V_TVALID = ap_const_logic_0)) or ((ap_predicate_op19_read_state1 = ap_const_boolean_1) and (s_axis_mem_read_cmd_V_TVALID = ap_const_logic_0)) or ((ap_predicate_op12_read_state1 = ap_const_boolean_1) and (s_axis_tlb_interface_V_TVALID = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(s_axis_mem_write_cmd_V_TVALID, s_axis_mem_read_cmd_V_TVALID, s_axis_tlb_interface_V_TVALID, tmp_nbreadreq_fu_94_p3, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_predicate_op12_read_state1, ap_predicate_op19_read_state1, ap_block_state3_io, regslice_both_m_axis_dma_write_cmd_V_U_apdone_blk, regslice_both_m_axis_dma_read_cmd_V_U_apdone_blk, ap_block_state4_io)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state4_io) or (regslice_both_m_axis_dma_read_cmd_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_m_axis_dma_write_cmd_V_U_apdone_blk = ap_const_logic_1))) or ((ap_const_boolean_1 = ap_block_state3_io) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_logic_1 = ap_const_logic_1) and (((tmp_nbreadreq_fu_94_p3 = ap_const_lv1_1) and (s_axis_mem_write_cmd_V_TVALID = ap_const_logic_0)) or ((ap_predicate_op19_read_state1 = ap_const_boolean_1) and (s_axis_mem_read_cmd_V_TVALID = ap_const_logic_0)) or ((ap_predicate_op12_read_state1 = ap_const_boolean_1) and (s_axis_tlb_interface_V_TVALID = ap_const_logic_0)))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(s_axis_mem_write_cmd_V_TVALID, s_axis_mem_read_cmd_V_TVALID, s_axis_tlb_interface_V_TVALID, tmp_nbreadreq_fu_94_p3, ap_predicate_op12_read_state1, ap_predicate_op19_read_state1)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (((tmp_nbreadreq_fu_94_p3 = ap_const_lv1_1) and (s_axis_mem_write_cmd_V_TVALID = ap_const_logic_0)) or ((ap_predicate_op19_read_state1 = ap_const_boolean_1) and (s_axis_mem_read_cmd_V_TVALID = ap_const_logic_0)) or ((ap_predicate_op12_read_state1 = ap_const_boolean_1) and (s_axis_tlb_interface_V_TVALID = ap_const_logic_0)));
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_io_assign_proc : process(tmp_reg_526_pp0_iter1_reg, ap_predicate_op74_write_state3, m_axis_dma_write_cmd_V_TREADY_int, m_axis_dma_read_cmd_V_TREADY_int)
    begin
                ap_block_state3_io <= (((tmp_reg_526_pp0_iter1_reg = ap_const_lv1_1) and (m_axis_dma_write_cmd_V_TREADY_int = ap_const_logic_0)) or ((ap_predicate_op74_write_state3 = ap_const_boolean_1) and (m_axis_dma_read_cmd_V_TREADY_int = ap_const_logic_0)));
    end process;

        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state4_io_assign_proc : process(tmp_reg_526_pp0_iter2_reg, ap_predicate_op105_write_state4, m_axis_dma_write_cmd_V_TREADY_int, m_axis_dma_read_cmd_V_TREADY_int)
    begin
                ap_block_state4_io <= (((tmp_reg_526_pp0_iter2_reg = ap_const_lv1_1) and (m_axis_dma_write_cmd_V_TREADY_int = ap_const_logic_0)) or ((ap_predicate_op105_write_state4 = ap_const_boolean_1) and (m_axis_dma_read_cmd_V_TREADY_int = ap_const_logic_0)));
    end process;


    ap_block_state4_pp0_stage0_iter3_assign_proc : process(regslice_both_m_axis_dma_write_cmd_V_U_apdone_blk, regslice_both_m_axis_dma_read_cmd_V_U_apdone_blk)
    begin
                ap_block_state4_pp0_stage0_iter3 <= ((regslice_both_m_axis_dma_read_cmd_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_m_axis_dma_write_cmd_V_U_apdone_blk = ap_const_logic_1));
    end process;


    ap_condition_202_assign_proc : process(tmp_reg_526, tmp_1_reg_535, tmp_2_reg_539)
    begin
                ap_condition_202 <= ((tmp_1_reg_535 = ap_const_lv1_0) and (tmp_reg_526 = ap_const_lv1_0) and (tmp_2_reg_539 = ap_const_lv1_1));
    end process;


    ap_condition_244_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_244 <= ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001));
    end process;


    ap_condition_247_assign_proc : process(tmp_nbreadreq_fu_94_p3, tmp_1_nbreadreq_fu_102_p3, tmp_2_nbreadreq_fu_110_p3, tmp_4_fu_234_p3)
    begin
                ap_condition_247 <= ((tmp_1_nbreadreq_fu_102_p3 = ap_const_lv1_0) and (tmp_4_fu_234_p3 = ap_const_lv1_1) and (tmp_2_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (tmp_nbreadreq_fu_94_p3 = ap_const_lv1_0));
    end process;


    ap_condition_253_assign_proc : process(tmp_nbreadreq_fu_94_p3, tmp_1_nbreadreq_fu_102_p3, tmp_2_nbreadreq_fu_110_p3, tmp_4_fu_234_p3)
    begin
                ap_condition_253 <= ((tmp_1_nbreadreq_fu_102_p3 = ap_const_lv1_0) and (tmp_4_fu_234_p3 = ap_const_lv1_0) and (tmp_2_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (tmp_nbreadreq_fu_94_p3 = ap_const_lv1_0));
    end process;


    ap_condition_257_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
                ap_condition_257 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_base_vaddr_V_loc_0_reg_193 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op105_write_state4_assign_proc : process(tmp_reg_526_pp0_iter2_reg, tmp_1_reg_535_pp0_iter2_reg)
    begin
                ap_predicate_op105_write_state4 <= ((tmp_reg_526_pp0_iter2_reg = ap_const_lv1_0) and (tmp_1_reg_535_pp0_iter2_reg = ap_const_lv1_1));
    end process;


    ap_predicate_op12_read_state1_assign_proc : process(tmp_nbreadreq_fu_94_p3, tmp_1_nbreadreq_fu_102_p3, tmp_2_nbreadreq_fu_110_p3)
    begin
                ap_predicate_op12_read_state1 <= ((tmp_1_nbreadreq_fu_102_p3 = ap_const_lv1_0) and (tmp_2_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (tmp_nbreadreq_fu_94_p3 = ap_const_lv1_0));
    end process;


    ap_predicate_op19_read_state1_assign_proc : process(tmp_nbreadreq_fu_94_p3, tmp_1_nbreadreq_fu_102_p3)
    begin
                ap_predicate_op19_read_state1 <= ((tmp_1_nbreadreq_fu_102_p3 = ap_const_lv1_1) and (tmp_nbreadreq_fu_94_p3 = ap_const_lv1_0));
    end process;


    ap_predicate_op74_write_state3_assign_proc : process(tmp_reg_526_pp0_iter1_reg, tmp_1_reg_535_pp0_iter1_reg)
    begin
                ap_predicate_op74_write_state3 <= ((tmp_reg_526_pp0_iter1_reg = ap_const_lv1_0) and (tmp_1_reg_535_pp0_iter1_reg = ap_const_lv1_1));
    end process;

    ap_reset_idle_pp0 <= ap_const_logic_0;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_fu_202_p2 <= std_logic_vector(unsigned(tlbMissCounter_V) + unsigned(ap_const_lv32_1));
    grp_fu_214_p2 <= std_logic_vector(unsigned(tlbPageCrossingCount) + unsigned(ap_const_lv32_1));
    icmp_ln895_1_fu_452_p2 <= "1" when (unsigned(ret_V_fu_446_p2) > unsigned(ap_const_lv33_200000)) else "0";
    icmp_ln895_2_fu_404_p2 <= "1" when (unsigned(r_V_1_reg_568) > unsigned(zext_ln895_1_fu_400_p1)) else "0";
    icmp_ln895_3_fu_421_p2 <= "1" when (unsigned(ret_V_1_fu_415_p2) > unsigned(ap_const_lv33_200000)) else "0";
    icmp_ln895_4_fu_374_p2 <= "1" when (unsigned(r_V_2_fu_355_p4) > unsigned(zext_ln895_2_fu_370_p1)) else "0";
    icmp_ln895_fu_435_p2 <= "1" when (unsigned(r_V_reg_590) > unsigned(zext_ln895_fu_431_p1)) else "0";

    m_axis_dma_read_cmd_V_TDATA_blk_n_assign_proc : process(ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, tmp_reg_526_pp0_iter1_reg, ap_enable_reg_pp0_iter3, tmp_reg_526_pp0_iter2_reg, tmp_1_reg_535_pp0_iter1_reg, tmp_1_reg_535_pp0_iter2_reg, m_axis_dma_read_cmd_V_TREADY_int)
    begin
        if ((((tmp_reg_526_pp0_iter2_reg = ap_const_lv1_0) and (tmp_1_reg_535_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((tmp_reg_526_pp0_iter1_reg = ap_const_lv1_0) and (tmp_1_reg_535_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)))) then 
            m_axis_dma_read_cmd_V_TDATA_blk_n <= m_axis_dma_read_cmd_V_TREADY_int;
        else 
            m_axis_dma_read_cmd_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

        m_axis_dma_read_cmd_V_TDATA_int <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_3_fu_475_p3),96));

    m_axis_dma_read_cmd_V_TVALID <= regslice_both_m_axis_dma_read_cmd_V_U_vld_out;

    m_axis_dma_read_cmd_V_TVALID_int_assign_proc : process(ap_enable_reg_pp0_iter2, ap_predicate_op74_write_state3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op74_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axis_dma_read_cmd_V_TVALID_int <= ap_const_logic_1;
        else 
            m_axis_dma_read_cmd_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    m_axis_dma_write_cmd_V_TDATA_blk_n_assign_proc : process(ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, tmp_reg_526_pp0_iter1_reg, ap_enable_reg_pp0_iter3, tmp_reg_526_pp0_iter2_reg, m_axis_dma_write_cmd_V_TREADY_int)
    begin
        if ((((tmp_reg_526_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((tmp_reg_526_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)))) then 
            m_axis_dma_write_cmd_V_TDATA_blk_n <= m_axis_dma_write_cmd_V_TREADY_int;
        else 
            m_axis_dma_write_cmd_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

        m_axis_dma_write_cmd_V_TDATA_int <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_12_fu_504_p3),96));

    m_axis_dma_write_cmd_V_TVALID <= regslice_both_m_axis_dma_write_cmd_V_U_vld_out;

    m_axis_dma_write_cmd_V_TVALID_int_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_reg_526_pp0_iter1_reg, ap_block_pp0_stage0_11001)
    begin
        if (((tmp_reg_526_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axis_dma_write_cmd_V_TVALID_int <= ap_const_logic_1;
        else 
            m_axis_dma_write_cmd_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;

    page_offset_V_1_fu_278_p1 <= addr_V_1_fu_272_p2(21 - 1 downto 0);
    page_offset_V_fu_322_p1 <= addr_V_fu_316_p2(21 - 1 downto 0);
    r_V_2_fu_355_p4 <= addr_V_2_fu_350_p2(63 downto 21);
    r_V_6_fu_427_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_V_reg_590),64));
    r_V_7_fu_396_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_V_1_reg_568),64));
    r_V_8_fu_365_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_V_2_fu_355_p4),64));
    regPageCrossingCount_V <= std_logic_vector(unsigned(tlbPageCrossingCount) + unsigned(ap_const_lv32_1));

    regPageCrossingCount_V_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter3, tmp_reg_526_pp0_iter2_reg, tmp_1_reg_535_pp0_iter2_reg, ap_block_pp0_stage0_11001, icmp_ln895_3_reg_614_pp0_iter2_reg, icmp_ln895_1_reg_627_pp0_iter2_reg)
    begin
        if ((((tmp_reg_526_pp0_iter2_reg = ap_const_lv1_0) and (tmp_1_reg_535_pp0_iter2_reg = ap_const_lv1_1) and (icmp_ln895_3_reg_614_pp0_iter2_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_reg_526_pp0_iter2_reg = ap_const_lv1_1) and (icmp_ln895_1_reg_627_pp0_iter2_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            regPageCrossingCount_V_ap_vld <= ap_const_logic_1;
        else 
            regPageCrossingCount_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    regTlbMissCount_V <= std_logic_vector(unsigned(tlbMissCounter_V) + unsigned(ap_const_lv32_1));

    regTlbMissCount_V_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter3, tmp_reg_526_pp0_iter2_reg, tmp_1_reg_535_pp0_iter2_reg, ap_block_pp0_stage0_11001, icmp_ln895_2_reg_610_pp0_iter2_reg, icmp_ln895_reg_623_pp0_iter2_reg)
    begin
        if ((((tmp_reg_526_pp0_iter2_reg = ap_const_lv1_0) and (tmp_1_reg_535_pp0_iter2_reg = ap_const_lv1_1) and (icmp_ln895_2_reg_610_pp0_iter2_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_reg_526_pp0_iter2_reg = ap_const_lv1_1) and (icmp_ln895_reg_623_pp0_iter2_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            regTlbMissCount_V_ap_vld <= ap_const_logic_1;
        else 
            regTlbMissCount_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    ret_V_1_fu_415_p2 <= std_logic_vector(unsigned(zext_ln215_2_fu_409_p1) + unsigned(zext_ln215_3_fu_412_p1));
    ret_V_fu_446_p2 <= std_logic_vector(unsigned(zext_ln215_fu_440_p1) + unsigned(zext_ln215_1_fu_443_p1));

    s_axis_mem_read_cmd_V_TDATA_blk_n_assign_proc : process(s_axis_mem_read_cmd_V_TVALID, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, tmp_nbreadreq_fu_94_p3, tmp_1_nbreadreq_fu_102_p3)
    begin
        if (((tmp_1_nbreadreq_fu_102_p3 = ap_const_lv1_1) and (tmp_nbreadreq_fu_94_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            s_axis_mem_read_cmd_V_TDATA_blk_n <= s_axis_mem_read_cmd_V_TVALID;
        else 
            s_axis_mem_read_cmd_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    s_axis_mem_read_cmd_V_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_predicate_op19_read_state1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op19_read_state1 = ap_const_boolean_1) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            s_axis_mem_read_cmd_V_TREADY <= ap_const_logic_1;
        else 
            s_axis_mem_read_cmd_V_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    s_axis_mem_write_cmd_V_TDATA_blk_n_assign_proc : process(s_axis_mem_write_cmd_V_TVALID, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, tmp_nbreadreq_fu_94_p3)
    begin
        if (((tmp_nbreadreq_fu_94_p3 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            s_axis_mem_write_cmd_V_TDATA_blk_n <= s_axis_mem_write_cmd_V_TVALID;
        else 
            s_axis_mem_write_cmd_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    s_axis_mem_write_cmd_V_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, tmp_nbreadreq_fu_94_p3, ap_block_pp0_stage0_11001)
    begin
        if (((tmp_nbreadreq_fu_94_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            s_axis_mem_write_cmd_V_TREADY <= ap_const_logic_1;
        else 
            s_axis_mem_write_cmd_V_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    s_axis_tlb_interface_V_TDATA_blk_n_assign_proc : process(s_axis_tlb_interface_V_TVALID, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, tmp_nbreadreq_fu_94_p3, tmp_1_nbreadreq_fu_102_p3, tmp_2_nbreadreq_fu_110_p3)
    begin
        if (((tmp_1_nbreadreq_fu_102_p3 = ap_const_lv1_0) and (tmp_2_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (tmp_nbreadreq_fu_94_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            s_axis_tlb_interface_V_TDATA_blk_n <= s_axis_tlb_interface_V_TVALID;
        else 
            s_axis_tlb_interface_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    s_axis_tlb_interface_V_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_predicate_op12_read_state1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op12_read_state1 = ap_const_boolean_1) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            s_axis_tlb_interface_V_TREADY <= ap_const_logic_1;
        else 
            s_axis_tlb_interface_V_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    tlb_table_paddr_V_address0_assign_proc : process(tmp_reg_526, tmp_1_reg_535, r_V_8_fu_365_p1, r_V_7_fu_396_p1, r_V_6_fu_427_p1, ap_condition_202, ap_condition_257)
    begin
        if ((ap_const_boolean_1 = ap_condition_257)) then
            if ((tmp_reg_526 = ap_const_lv1_1)) then 
                tlb_table_paddr_V_address0 <= r_V_6_fu_427_p1(14 - 1 downto 0);
            elsif (((tmp_reg_526 = ap_const_lv1_0) and (tmp_1_reg_535 = ap_const_lv1_1))) then 
                tlb_table_paddr_V_address0 <= r_V_7_fu_396_p1(14 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_202)) then 
                tlb_table_paddr_V_address0 <= r_V_8_fu_365_p1(14 - 1 downto 0);
            else 
                tlb_table_paddr_V_address0 <= "XXXXXXXXXXXXXX";
            end if;
        else 
            tlb_table_paddr_V_address0 <= "XXXXXXXXXXXXXX";
        end if; 
    end process;


    tlb_table_paddr_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, tmp_reg_526, tmp_1_reg_535, ap_block_pp0_stage0_11001, tmp_2_reg_539, ap_enable_reg_pp0_iter1)
    begin
        if ((((tmp_reg_526 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_reg_526 = ap_const_lv1_0) and (tmp_1_reg_535 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_1_reg_535 = ap_const_lv1_0) and (tmp_reg_526 = ap_const_lv1_0) and (tmp_2_reg_539 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            tlb_table_paddr_V_ce0 <= ap_const_logic_1;
        else 
            tlb_table_paddr_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    tlb_table_paddr_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, tmp_reg_526, tmp_1_reg_535, ap_block_pp0_stage0_11001, tmp_2_reg_539, ap_enable_reg_pp0_iter1)
    begin
        if (((tmp_1_reg_535 = ap_const_lv1_0) and (tmp_reg_526 = ap_const_lv1_0) and (tmp_2_reg_539 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            tlb_table_paddr_V_we0 <= ap_const_logic_1;
        else 
            tlb_table_paddr_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_12_fu_504_p3 <= (tmp_len_V_reg_596_pp0_iter1_reg & zext_ln78_1_fu_500_p1);
    tmp_1_nbreadreq_fu_102_p3 <= (0=>(s_axis_mem_read_cmd_V_TVALID), others=>'-');
    tmp_2_nbreadreq_fu_110_p3 <= (0=>(s_axis_tlb_interface_V_TVALID), others=>'-');
    tmp_3_fu_475_p3 <= (tmp_len_V_1_reg_574_pp0_iter1_reg & zext_ln78_3_fu_471_p1);
    tmp_4_fu_234_p3 <= s_axis_tlb_interface_V_TDATA(128 downto 128);
    tmp_addr_V_1_fu_465_p2 <= std_logic_vector(unsigned(zext_ln78_2_fu_461_p1) + unsigned(zext_ln214_1_fu_458_p1));
    tmp_addr_V_fu_494_p2 <= std_logic_vector(unsigned(zext_ln78_fu_490_p1) + unsigned(zext_ln214_fu_487_p1));
    tmp_nbreadreq_fu_94_p3 <= (0=>(s_axis_mem_write_cmd_V_TVALID), others=>'-');
    trunc_ln321_1_fu_258_p1 <= s_axis_mem_read_cmd_V_TDATA(64 - 1 downto 0);
    trunc_ln321_2_fu_230_p1 <= s_axis_tlb_interface_V_TDATA(64 - 1 downto 0);
    trunc_ln321_fu_302_p1 <= s_axis_mem_write_cmd_V_TDATA(64 - 1 downto 0);
    zext_ln214_1_fu_458_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(page_offset_V_1_reg_562_pp0_iter1_reg),49));
    zext_ln214_fu_487_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(page_offset_V_reg_584_pp0_iter1_reg),49));
    zext_ln215_1_fu_443_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_len_V_load_new_reg_579),33));
    zext_ln215_2_fu_409_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(page_offset_V_1_reg_562),33));
    zext_ln215_3_fu_412_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_len_V_2_load_new_reg_557),33));
    zext_ln215_fu_440_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(page_offset_V_reg_584),33));
    zext_ln78_1_fu_500_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_addr_V_fu_494_p2),64));
    zext_ln78_2_fu_461_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tlb_table_paddr_V_q0),49));
    zext_ln78_3_fu_471_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_addr_V_1_fu_465_p2),64));
    zext_ln78_fu_490_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tlb_table_paddr_V_q0),49));
    zext_ln895_1_fu_400_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(top_page_base_V),43));
    zext_ln895_2_fu_370_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(top_page_base_V),43));
    zext_ln895_fu_431_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(top_page_base_V),43));
end behav;
